### PR TITLE
Adding Java String example

### PR DESCRIPTION
**Pull request by gaurangagarwal**
#### 1. I have added a few examples for `JavaString` in the repo.
* Convert the String to Lower case
* Find number of characters in String
* Find a character at particular position in String
* Concatenation
* Finds a Substring in the given String
### Testing
Output
```
Sample String : Hello World
String in Lower case is hello world
Length of the String is 11
Char at position 4 is o
Concatenated with  Happy Coding results in Hello World Happy Coding
SubString from 0 to 4 is Hell
```

### CODE REVIEW

**Comment by owais4321** [comment]
Kindly checkout the Java String/README.md file update yours according to it otherwise there is a conflict 
Thanks

**Comment by gaurangagarwal** [comment]
Created a new commit to resolve the merge conflict. 
Thank you. 👍

**Comment by gaurangagarwal** [comment]
Can you please provide an update ?

**Comment by owais4321** [comment]
There is a conflict kindly resolve it Thanks

**Comment by gaurangagarwal** [comment]
Till the time you try to merge my commit, there is another pull request which is merged even before mine causing a conflict. :P

**Comment by owais4321** [comment]
Your pull request is merged thanks

**Pull request merged**
