### PR TITLE
Added description

### PR DESCRIPTION
**Pull request by jmrchelani**
added description to readme files

### CODE REVIEW

**Comment by owais4321** [comment]
Kindly check the news version of README.md file and update it accordingly

**Comment by jmrchelani** [comment]
Java String Readme is fixed and the Variable and Data Types documentation in the main branch is not better than the one I committed so maybe merge it.

**Comment by owais4321** [comment]
There are two conflicts resolve them i will merge it

**Comment by owais4321** [comment]
Still some conflicts

**Comment by jmrchelani** [comment]
No conflicts anymore

**Comment by owais4321** [comment]
Congratulations @jmrchelani  your PR has been merged

**Comment by jmrchelani** [comment]
thanks

**Pull request merged**
